### ISSUE TITLE
오늘은 몇주차 오류

### ISSUE THREAD

**Issue by cwpraha** [nyeong/hanassig#15]
안녕하세요 개발자님!
예전에 "오늘은 몇주차!" 페이지를 발견하여 즐겨찾기에 등록해두고 종종 잘 쓰고 있습니다!
오늘 페이지에 접속해보니 아래와 같이 떠서 여기에 글 남깁니다. 모종의 이유로 페이지를 삭제하신거면 어쩔수없겠네요 ㅎㅎ

페이지를 찾을 수 없습니다.
원하는 페이지를 찾을 수 없습니다.
사이트 관리자에게 링크가 깨진 것을 알려주세요.

**Comment by nyeong** [comment]
안녕하세요. 사이트를 유용하게 써 주셔서 감사합니다. 🙂

도메인의 용도를 바꾸며 해당 사이트는 다음의 주소로 변경되었습니다: https://nyeong.github.io/nth-week-today/

설마 즐겨찾기에 등록해주시고 사용해주실 줄은 몰랐습니다. 본래의 주소로도 접속할 수 있도록 방법을 찾아보겠습니다.

**Comment by nyeong** [comment]
[https://annyeong.me/nth-week-today](https://annyeong.me/nth-week-today)에 리다이렉션을 추가하였습니다. 본래 쓰던 주소로 쓰실 수 있을 겁니다.
관심 가져주셔서 감사합니다 🙇‍♂️

**Comment by cwpraha** [comment]
앗 개발자님! 저를 위해 수정해주시다니, 감사합니다! 
오늘도 좋은 하루 되시고, 하시는 일 잘 되길 바라겠습니다!
